"""initial_schema

Revision ID: e034336fbdef
Revises: 
Create Date: 2026-03-06 18:14:11.356309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e034336fbdef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('terminal', sa.String(length=100), nullable=True),
    sa.Column('berth_type', sa.Enum('CONTAINER', 'BULK', 'TANKER', 'RO_RO', 'GENERAL', 'MULTIPURPOSE', name='berthtype'), nullable=False),
    sa.Column('max_length', sa.Float(), nullable=False),
    sa.Column('max_beam', sa.Float(), nullable=True),
    sa.Column('max_draft', sa.Float(), nullable=False),
    sa.Column('max_tonnage', sa.Float(), nullable=True),
    sa.Column('has_crane', sa.Boolean(), nullable=False),
    sa.Column('crane_capacity_tons', sa.Float(), nullable=True),
    sa.Column('has_pipeline', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'RESERVED', name='berthstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berths_code'), 'berths', ['code'], unique=True)
    op.create_index(op.f('ix_berths_id'), 'berths', ['id'], unique=False)
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imo_number', sa.String(length=20), nullable=False),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vessel_type', sa.Enum('CONTAINER', 'BULK_CARRIER', 'TANKER', 'RO_RO', 'GENERAL_CARGO', 'OTHER', name='vesseltype'), nullable=False),
    sa.Column('flag', sa.String(length=50), nullable=True),
    sa.Column('length_overall', sa.Float(), nullable=True),
    sa.Column('beam', sa.Float(), nullable=True),
    sa.Column('max_draft', sa.Float(), nullable=True),
    sa.Column('gross_tonnage', sa.Float(), nullable=True),
    sa.Column('deadweight_tonnage', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('AT_SEA', 'APPROACHING', 'ANCHORED', 'BERTHED', 'DEPARTED', name='vesselstatus'), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('current_speed', sa.Float(), nullable=True),
    sa.Column('current_heading', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mmsi')
    )
    op.create_index(op.f('ix_vessels_id'), 'vessels', ['id'], unique=False)
    op.create_index(op.f('ix_vessels_imo_number'), 'vessels', ['imo_number'], unique=True)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('berth_id', sa.Integer(), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etb', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ata', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atb', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cargo_type', sa.Enum('CONTAINERS', 'BULK_DRY', 'BULK_LIQUID', 'GENERAL', 'RO_RO', 'PASSENGER', 'OTHER', name='cargotype'), nullable=True),
    sa.Column('cargo_quantity', sa.Float(), nullable=True),
    sa.Column('cargo_unit', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'APPROACHING', 'ANCHORED', 'BERTHING', 'IN_PORT', 'DEPARTING', 'COMPLETED', 'CANCELLED', name='visitstatus'), nullable=False),
    sa.Column('voyage_number', sa.String(length=50), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('waiting_time_hours', sa.Float(), nullable=True),
    sa.Column('berth_time_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_berth_id'), 'visits', ['berth_id'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_vessel_id'), 'visits', ['vessel_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.Enum('ETA', 'ETB', 'BERTH_CONGESTION', 'WAITING_TIME', 'BERTH_ASSIGNMENT', name='predictiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'SUPERSEDED', name='predictionstatus'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('predicted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('input_features', sa.JSON(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('actual_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_mae', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_vessel_id'), 'predictions', ['vessel_id'], unique=False)
    op.create_index(op.f('ix_predictions_visit_id'), 'predictions', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_visit_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_vessel_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_visits_vessel_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_berth_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_vessels_imo_number'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_id'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_berths_id'), table_name='berths')
    op.drop_index(op.f('ix_berths_code'), table_name='berths')
    op.drop_table('berths')
    # ### end Alembic commands ###
